[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
engine = { path = "crates/engine" }
axum = "0.8.9"
clap = { version = "4.6.7", features = ["derive"] }
fastrand = "2.5.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["fs", "macros", "net", "rt-multi-thread"] }
